# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'number_speaker_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NumberSpeaker(object):
    def setupUi(self, NumberSpeaker):
        NumberSpeaker.setObjectName("NumberSpeaker")
        NumberSpeaker.resize(500, 250)
        NumberSpeaker.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        NumberSpeaker.setLayoutDirection(QtCore.Qt.LeftToRight)
        NumberSpeaker.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(NumberSpeaker)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 411, 51))
        font = QtGui.QFont()
        font.setFamily("Acknowledgement")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setMaxLength(20)
        self.lineEdit.setObjectName("lineEdit")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setEnabled(False)
        self.textEdit.setGeometry(QtCore.QRect(20, 80, 461, 87))
        font = QtGui.QFont()
        font.setFamily("Boogaloo")
        font.setPointSize(10)
        self.textEdit.setFont(font)
        self.textEdit.setReadOnly(True)
        self.textEdit.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Boogaloo\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt;\">Result will be shown here</span></p></body></html>")
        self.textEdit.setObjectName("textEdit")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(360, 180, 111, 41))
        self.pushButton_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 180, 111, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(430, 10, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Acknowledgement")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        NumberSpeaker.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(NumberSpeaker)
        self.statusbar.setObjectName("statusbar")
        NumberSpeaker.setStatusBar(self.statusbar)

        self.retranslateUi(NumberSpeaker)
        QtCore.QMetaObject.connectSlotsByName(NumberSpeaker)

    def retranslateUi(self, NumberSpeaker):
        _translate = QtCore.QCoreApplication.translate
        NumberSpeaker.setWindowTitle(_translate("NumberSpeaker", "Number Speaker"))
        self.lineEdit.setPlaceholderText(_translate("NumberSpeaker", "Type your Number here ....."))
        self.pushButton_2.setText(_translate("NumberSpeaker", "Export Audio"))
        self.pushButton_3.setText(_translate("NumberSpeaker", "Play_Audio"))
        self.pushButton.setText(_translate("NumberSpeaker", ">"))
